name: Manhunt
version: '${project.version}'
main: com.github.zululi.minecrafthunters.Minecrafthunters
api-version: 1.16
commands:
  start:
    description: start the game.
  g:
    description: global chat
  settimer:
    description: a
  qs:
    description: quick start
  return:
    description: a
  test:
    description: a
  compass:
    description: a
  playerstats:
    description: a
  reloadleaderboard:
    description: a

